name: container-iac-scan

on:
  workflow_dispatch:
    

jobs:

  container-scan:
      runs-on: ubuntu-latest
      name: container iac scan

      steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: container-iac action
          id: container-scan
          uses: veracode/container_iac_secrets_scanning@v1.0.4
          with:
            vid: ${{ secrets.VERACODE_API_ID }}
            vkey: ${{ secrets.VERACODE_API_KEY }}
            command: "scan" 
            type: "directory"
            source: "./"
            format: "json"
            debug: false
            fail_build: false

        - name: container-iac-scan-results
          uses: actions/upload-artifact@v4 
          with:
            name: container-iac-scan-results
            path: /home/runner/work/verademo-js-api/veracode-cli/results.json
