on:
  workflow_dispatch:
#  pull_request:
#    branches: [main]
    

jobs:

  container-scan:
      runs-on: ubuntu-latest
      name: container scan

      steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: container-iac action
          id: container-scan
          uses: veracode/container_iac_secrets_scanning@v1.0.1
          with:
            vid: ${{ secrets.VERACODE_API_ID }}
            vkey: ${{ secrets.VERACODE_API_KEY }}
            command: "scan" 
            type: "directory"
            source: "./"
            format: "json"
            debug: true
            fail_build: true
