name: veracode-pipeline-scan
on:
  workflow_dispatch:


jobs:
    # Steps to build the application and store the artifact prior to scanning

    # Initiate the Pipeline Scan   
  pipeline_scan:
      needs: build
      runs-on: ubuntu-latest
      name: pipeline scan
      steps:
        - name: checkout repo
          uses: actions/checkout@v3

        - name: get archive
          uses: actions/download-artifact@v3
          with:
            name: veracode-auto-pack-verademo-js-api-js.zip
        - name: pipeline-scan action step
          id: pipelien-scan
          uses: veracode/Veracode-pipeline-scan-action@v1.0.12
          with:
            vid: ${{ secrets.VERACODE_API_ID }}
            vkey: ${{ secrets.VERACODE_API_KEY }}
            file: "veracode-auto-pack-verademo-js-api-js.zip" 
            request_policy: "VeraDemo Policy"
            debug: 1
            fail_build: false
