name: veracode-pipeline-scan
on:
  workflow_dispatch:


jobs:
    # Steps to build the application and store the artifact prior to scanning

    # Initiate the Pipeline Scan   
  pipeline_scan:
      runs-on: ubuntu-latest
      name: pipeline scan
      steps:
        - name: checkout repo
          uses: actions/checkout@v4
          with:
            sparse-checkout: |
              veracode-auto-pack-verademo-js-api-js.zip

        - name: pipeline-scan action step
          id: pipeline-scan
          uses: veracode/Veracode-pipeline-scan-action@v1.0.17
          with:
            vid: ${{ secrets.VERACODE_API_ID }}
            vkey: ${{ secrets.VERACODE_API_KEY }}
            file: "veracode-auto-pack-verademo-js-api-js.zip" 
            #veracode_policy_name: "High and Above and CVSS 7.0+"
            #debug: 1
            fail_build: false
