name: Veracode Policy Scan

on:
  workflow_dispatch:
  
jobs:


  policy_scan:
      runs-on: ubuntu-latest
      name: platform policy scan
      steps:
        - name: checkout repo
          uses: actions/checkout@v4
          with:
            sparse-checkout: |
              veracode-auto-pack-verademo-js-api-js.zip
        - name: Veracode Policy Upload and Scan
          id: policy-scan
          uses: veracode/veracode-uploadandscan-action@0.2.7
          with:
            appname: 'Verademo JS API'
            createprofile: false
            #policy: 'Verademo Policy'
            version: '${{ github.run_id }}'
            filepath: veracode-auto-pack-verademo-js-api-js.zip
            vid: '${{ secrets.VERACODE_API_ID }}'
            vkey: '${{ secrets.VERACODE_API_ID }}'
            scantimeout: 15
            deleteincompletescan: true
