name: veracode-sandbox-scan

on:
  workflow_dispatch:
  
jobs:
  sandbox_scan:
      runs-on: ubuntu-latest
      name: platform application sandbox scan
      steps:
        - name: checkout repo
          uses: actions/checkout@v4
          with:
            sparse-checkout: |
              veracode-auto-pack-verademo-js-api-js.zip
        - name: Veracode Sandbox Upload and Scan
          id: sandbox-scan
          uses: veracode/veracode-uploadandscan-action@0.2.7
          with:
            appname: 'Verademo JS API'
            createprofile: false
            #policy: 'Verademo Policy'
            version: '${{ github.run_id }}'
            filepath: veracode-auto-pack-verademo-js-api-js.zip
            vid: '${{ secrets.VERACODE_API_ID }}'
            vkey: '${{ secrets.VERACODE_API_KEY }}'
            #createsandbox: true
            sandboxname: 'GitHub Sandbox'
            scantimeout: 15
            deleteincompletescan: 1