name: sca-agent-scan
on:
  workflow_dispatch:

jobs:
  veracode-sca-task1:
    runs-on: ubuntu-latest
    name: SCA agent-scan

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Veracode SCA agent scan
        env:
            SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: veracode/veracode-sca@2.1.12
        with:
          create-issues: false
          artifactname: scan1
          debug: true

