name: update-repo-keys

on:
  workflow_dispatch:

jobs:

  update-keys:
      runs-on: ubuntu-latest
      steps:
        - name: checkout repo
          uses: actions/checkout@v4
        - name: get keys
          run: gh secret list
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
