name: veracode-fix-action
on:
  pull_request:
    branches: [main]
  workflow_dispatch:



jobs:
  pipeline_scan:
      runs-on: ubuntu-latest
      name: pipeline scan
      steps:
        - name: checkout repo
          uses: actions/checkout@v4
          with:
            sparse-checkout: |
              veracode-auto-pack-verademo-js-api-js.zip

        - name: pipeline-scan action step
          id: pipeline-scan
          uses: veracode/Veracode-pipeline-scan-action@v1.0.18
          with:
            vid: ${{ secrets.VERACODE_API_ID }}
            vkey: ${{ secrets.VERACODE_API_KEY }}
            file: "veracode-auto-pack-verademo-js-api-js.zip" 
            #veracode_policy_name: "High and Above and CVSS 7.0+"
            #debug: 1
            fail_build: false
        - uses: actions/upload-artifact@v4
          with:
            name: Veracode Pipeline-Scan Results
            path: results.json

  veracode-fix:
    runs-on: ubuntu-latest
    needs: pipeline_scan
    name: create fixes
    permissions: write-all
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: get flaw file
        uses: actions/download-artifact@v4
        with:
          name: Veracode Pipeline-Scan Results
          
      - name: Create fixes from static findings
        id: convert
        uses: Veracode/veracode-fix@main
        with:
          inputFile: results.json
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          #source_base_path_1: "com/:src/main/java/com/"
          #source_base_path_2: "WEB-INF:src/main/webapp/WEB-INF"
          language: javascript
          cwe: 89,117
          fixType: 'single'
          debug: false
          prComment: true
          files: 'all'
          codeSuggestion: false
          createPR: true
